# SPDX-License-Identifier: Apache-2.0

[package]
name = "minimal-next-site"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "minimal-next-site"
path = "src/main.rs"
test = false
bench = false

[dependencies]
pliego-dom = { workspace = true }
pliego-ssg = { workspace = true }
