# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "stress-dashboard-next-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pliego-fold = { workspace = true }
pliego-log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }
pliego-dom = { workspace = true }
pliego-reactive = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
